# Generated by Django 3.1 on 2020-09-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200902_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
